import ClientProvider from '@/components/ClientProvider'
import SideBar from '@/components/SideBar'
import '@/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          {/* sidebar */}
          <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
            <SideBar/>
            </div>
          <ClientProvider ></ClientProvider>
        <div className='bg-[#343541] flex-1'>
          {children}
        </div >
        </div>
      </body>
    </html>
  )
}
